version: '3.8'

services:
  api:
    container_name: codechat_api
    image: codechat/api:v1.3.4
    restart: unless-stopped
    ports:
      - 8084:8084
    volumes:
      - instances_connecteds:/codechat/instances
    environment:
      - SERVER_PORT=8084
      - SESSION_SECRET=W0NvZGVDaGF0XTpbU2Vzc

      - LOG_LEVEL=ERROR|WARN|INFO|DEBUG|LOG|VERBOSE|DARK
      - LOG_COLOR=true

      - DATABASE_ENABLED=true
      - DATABASE_URL=postgres://postgres:smb@postgres_server_smb:5432/smb_db?schema=public
      - DATABASE_SYNC_MESSAGES=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true

      - GLOBAL_WEBHOOK_URL=url
      - GLOBAL_WEBHOOK_ENABLED=false

      - INSTANCE_EXPIRATION_TIME=false

      - CONFIG_SESSION_PHONE_CLIENT=CodeChat_V1
      - CONFIG_SESSION_PHONE_NAME=Edge

      - WA_VERSION=[ 2, 3000, 1023247615 ]

      - QRCODE_LIMIT=10
      - QRCODE_EXPIRATION_TIME=60

      - CONNECTION_TIMEOUT=300

      - AUTHENTICATION_GLOBAL_AUTH_TOKEN=zYzP7ocstxh3SJ23D4FZTCu4ehnM8v4hu
      - AUTHENTICATION_JWT_EXPIRES_IN=0
      - AUTHENTICATION_JWT_SECRET=3RFYiiRmvNiokSBrLZzx

      - PROVIDER_ENABLED=false
      - PROVIDER_HOST=127.0.0.1
      - PROVIDER_PORT=5656
      - PROVIDER_PREFIX=codechat

      - BASE_URL=
    networks:
      - public_network

  postgres_server:
    image: postgres:latest
    container_name: postgres_server_smb
    environment:
      POSTGRES_PASSWORD: 'smb'
      POSTGRES_DB: smb_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - public_network

volumes:
  instances_connecteds:
    external: true
  postgres_data:

networks:
  public_network:
    driver: bridge
